# Generated by Django 4.0.5 on 2022-06-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('practical', 'Practical'), ('advanced', 'Advanced'), ('professional', 'Professional')], max_length=20),
        ),
    ]
