# Generated by Django 4.0.5 on 2022-06-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkills', '0002_alter_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(max_length=288, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
