# Generated by Django 4.0.5 on 2022-06-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkills', '0008_alter_skill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='example',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Practical', 'Practical'), ('Advanced', 'Advanced'), ('Professional', 'Professional')], max_length=20),
        ),
    ]
