# Generated by Django 4.0.5 on 2022-06-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkills', '0009_alter_skill_description_alter_skill_example_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='skill',
            name='example',
            field=models.CharField(default='', max_length=150),
        ),
    ]
