# Generated by Django 4.0.5 on 2022-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkills', '0010_alter_skill_description_alter_skill_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='skill',
            name='example',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
