# Generated by Django 4.0.5 on 2022-06-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkills', '0012_alter_skill_description_alter_skill_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='skill',
            name='example',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Practical'), (4, 'Advanced'), (5, 'Professional')]),
        ),
    ]
