# Generated by Django 4.0.5 on 2022-06-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkills', '0013_alter_skill_description_alter_skill_example_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(choices=[]),
        ),
    ]
