# Generated by Django 4.0.5 on 2022-06-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkills', '0015_alter_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='exampleName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Practical'), (4, 'Advanced'), (5, 'Professional')], max_length=20),
        ),
    ]
