# Generated by Django 4.0.5 on 2022-06-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkills', '0016_skill_examplename_alter_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Practical'), (4, 'Advanced'), (5, 'Professional')]),
        ),
    ]
