# Generated by Django 4.0.5 on 2022-06-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSkills', '0019_alter_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='levelRank',
        ),
    ]
