# Generated by Django 4.0.5 on 2022-06-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSkills', '0020_remove_skill_levelrank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='example',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='exampleName',
        ),
        migrations.CreateModel(
            name='SkillExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exampleName', models.CharField(blank=True, default='', max_length=50)),
                ('exampleURLs', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('skillID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSkills.skill')),
            ],
        ),
    ]
