# Generated by Django 4.0.5 on 2022-06-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSkills', '0021_remove_skill_description_remove_skill_example_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillexample',
            name='exampleName',
        ),
        migrations.RemoveField(
            model_name='skillexample',
            name='exampleURLs',
        ),
        migrations.AddField(
            model_name='skillexample',
            name='URLs',
            field=models.CharField(default='test.com', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillexample',
            name='title',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skillexample',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
